/**
 * taro-ui 兼容入口, 带 `At` 前缀.
 * @packageDocumentation
 */

export {
    ActionSheet as AtActionSheet,
    ActionSheetProps as AtActionSheetProps,
    ActivityIndicator as AtActivityIndicator,
    Avatar as AtAvatar,
    Badge as AtBadge,
    Button as AtButton,
    Calendar as AtCalendar,
    CustomTabBar as AtCustomTabBar,
    FloatLayout as AtFloatLayout,
    FloatLayoutProps as AtFloatLayoutProps,
    Form as AtForm,
    Icon as AtIcon,
    IconProps as AtIconProps,
    ImagePicker as AtImagePicker,
    ImagePickerProps as AtImagePickerProps,
    Input as AtInput,
    InputProps as AtInputProps,
    InputNumber as AtInputNumber,
    InputNumberProps as AtInputNumberProps,
    List as AtList,
    ListHeader as AtListHeader,
    ListItem as AtListItem,
    Message as AtMessage,
    Modal as AtModal,
    ModalProps as AtModalProps,
    Progress as AtProgress,
    Statistic as AtStatistic,
    Steps as AtSteps,
    TabBar as AtTabBar,
    Tabs as AtTabs,
    TabsPane as AtTabsPane,
    Tag as AtTag,
    Textarea as AtTextarea,
    TextareaProps as AtTextareaProps,
} from './index'
